[package]
name = "file-service"
version = "0.1.0"
authors = ["Ryan Plauche <ryan@kubos.co>"]

[dependencies]
simplelog = "^0.5.0"
log = "^0.4.0"
cbor-protocol = { path = "../../libs/cbor-protocol" }
file-protocol = { path = "../../libs/file-protocol" }
kubos-system = { path = "../../apis/system-api" }
serde_cbor = "0.8"

[dev-dependencies]
blake2-rfc = "0.2.18"
rand = "0.5.5"
tempfile = "3"
